repo: 'contact-list-generator'

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    has:
      - 'script[src="js/contacts.js"]'
      - 'script[src="js/main.js"]'
      - ['script[src="js/contacts.js"] + script[src="js/main.js"]', 'The `contacts.js` file must come before the `main.js` file.']
    hasNot:
      - ['link', 'CSS isn’t necessary to complete this assignment']
      - ['body :not(script)', 'The `<script>` tag should be the only tag inside `<body>` — no other HTML is needed']

js:
  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - 'var listContacts = function \(contacts\) \{'
      - 'contacts\.forEach\(function \(item\) \{'
      - "document.write\\(\\'<h1>"
      - "document.write\\(\\'<h2>"
      - "document.write\\(\\'<dl>"
      - "document.write\\(\\'<dt>"
      - "document.write\\(\\'<\\/dl>"
      - '\+'
      - '<a href="tel:'
      - '<a href="mailto:'
      - 'km from the Sun\.'
      - 'Between'
      - 'Location'
      - 'E-mail address'
      - 'listContacts\(peeps\);'
  - path: 'js/contacts.js'
    valid: true
    bestPractices: true
    search:
      - 'var peeps = \['
      - 'name\:'
      - 'email\:'
      - 'tel\:'
      - 'loc\: \['
      - 'Mercury Man'
      - 'Venus ’Venturer'
      - 'Jupiter Juggernaut'
      - 'theman\@mercury\.com'
      - 'venus\@theadventurer\.com'
      - 'thejugger\@jupiter\.com'
      - '\+05551234'
      - '\+15551234'
      - '\+55551234'
      - '\];'

screenshots:
  - path: 'index.html'
    sizes: [400]

functionality:
  - path: 'index.html'
    tests:
      - |
        if (typeof listContacts !== 'function') fail('There’s no function named `listContacts()`');
        pass();
      - |
        if (!peeps) fail('The `peeps` variable doesn’t exist');
        if (peeps.constructor !== Array) fail('The `peeps` variable isn’t an array');
        if (peeps.length !== 3) fail('There aren’t the correct number of people in the `peeps` variable');
        if (typeof peeps[1] !== 'object') fail('Each person inside the `peeps` variable isn’t an object')
        if (peeps[1].name !== 'Venus ’Venturer') fail('The second person’s name doesn’t match “Venus ’Venturer”')
        if (peeps[1].email !== 'venus@theadventurer.com') fail('The second person’s email doesn’t match “venus@theadventurer.com”')
        if (peeps[1].tel !== '+15551234') fail('The second person’s telephone doesn’t match “+15551234”')
        if (peeps[1].loc.constructor !== Array) fail('The second person’s location isn’t an array');
        if (peeps[1].loc.length !== 2) fail('The second person’s location doesn’t have 2 pieces of information inside');

        pass();
